--********************************************************
-- TestDataInsert_ProdTests_Forms_Mortgage.sql
--********************************************************
-- Script to insert values for Form tests in Production - Mortgage
-- This data is designed so that it does not receive referrals in Production
--		Million Dollar Mobile Home in Montana
--		Secondary/Investment Property
--		Current Bankruptcy
--		Current Foreclosure
-- SELECT * FROM dbo.tTestData_Mortgage with(nolock) WHERE TestCaseName like 'Prod_%'

-- ************************************
-- ***** Insert Mortgage Tests    *****
-- ************************************

INSERT [dbo].[tTestData_Mortgage] ([TestCaseName], [TestEnvironment], [BrowserType], [Template], [Variation], [QueryString], [LoanType], [HomeDescription], [PropertyUseType], [PropertyState], [PropertyCity], [PropertyStreet], [PropertyZipCode], [FoundNewHomeYesNo], [FirstTimeBuyerYesNo], [PurchasePrice], [PurchaseDownPayment], [RefiPropertyValue], [FirstMortgageBalance], [FirstMortgagePayment], [FirstMortgageRate], [SecondMortgageYesNo], [SecondMortgageBalance], [SecondMortgagePayment], [SecondMortgageRate], [RefiCashoutAmount], [EmailAddress], [Password], [ConfirmPassword], [BorrowerFirstName], [BorrowerMiddleName], [BorrowerLastName], [BorrowerSuffix], [BorrowerStreetAddress], [BorrowerZipCode], [BorrowerHomePhone1], [BorrowerHomePhone2], [BorrowerHomePhone3], [BorrowerWorkPhone1], [BorrowerWorkPhone2], [BorrowerWorkPhone3], [BorrowerWorkPhoneExt], [WorkPhoneSameAsHomeYesNo], [BorrowerSsn1], [BorrowerSsn2], [BorrowerSsn3], [DateOfBirthMonth], [DateOfBirthDay], [DateOfBirthYear], [CreditProfile], [MilitaryServiceYesNo], [CurrentLoanVAYesNo], [ForeclosureHistory], [BankruptcyYesNo], [BankruptcyHistory], [CreditCardDebtAmount], [RealtorConsultYesNo], [DebtConsultYesNo], [MortgageInsuranceYesNo], [EmailOptInYesNo], [HomeServicesOptInYesNo], [CurrentREAgentYesNo], [CreditScoreProductYesNo], [EduOptInYesNo], [CcMessageToBorrower], [SpouseDateOfBirthMonth], [SpouseDateOfBirthDay], [SpouseDateOfBirthYear]) 
VALUES (N'Prod_MortTree_Refinance', N'PROD', N'firefox', N'mort-tree', N'2-0-0-0-0-0-1-0-0-3-2-0-1-0-1-0-0-1-0', N'&mpid=8550&devicemonitor=selenium', 
N'REFINANCE', N'Mobile/Manufactured home', N'Secondary home', N'Montana', N'Helena', N'', N'59602', N'', N'', N'', N'', N'Over $2,000,000', N'$900,001 - $950,000', 
N'Over $7,501', N'7.25%', N'N', N'', N'', N'', N'$0 No Cash', N'default', N'default', N'', N'Otto', N'', N'Tester', N'', N'11115 Rushmore Dr', N'28277', 
N'704', N'541', N'5351', N'407', N'939', N'3463', N'', N'N', N'default', N'default', N'default', N'01', N'02', N'1983', N'Good', N'Y', N'N', N'Currently in foreclosure', 
N'Y', N'1-12 months ago', N'$7500 - $9,999', N'N', N'N', N'N', N'N', N'N', N'N', N'N', N'N', N'', N'', N'', N'')
GO

INSERT [dbo].[tTestData_Mortgage] ([TestCaseName], [TestEnvironment], [BrowserType], [Template], [Variation], [QueryString], [LoanType], [HomeDescription], [PropertyUseType], [PropertyState], [PropertyCity], [PropertyStreet], [PropertyZipCode], [FoundNewHomeYesNo], [FirstTimeBuyerYesNo], [PurchasePrice], [PurchaseDownPayment], [RefiPropertyValue], [FirstMortgageBalance], [FirstMortgagePayment], [FirstMortgageRate], [SecondMortgageYesNo], [SecondMortgageBalance], [SecondMortgagePayment], [SecondMortgageRate], [RefiCashoutAmount], [EmailAddress], [Password], [ConfirmPassword], [BorrowerFirstName], [BorrowerMiddleName], [BorrowerLastName], [BorrowerSuffix], [BorrowerStreetAddress], [BorrowerZipCode], [BorrowerHomePhone1], [BorrowerHomePhone2], [BorrowerHomePhone3], [BorrowerWorkPhone1], [BorrowerWorkPhone2], [BorrowerWorkPhone3], [BorrowerWorkPhoneExt], [WorkPhoneSameAsHomeYesNo], [BorrowerSsn1], [BorrowerSsn2], [BorrowerSsn3], [DateOfBirthMonth], [DateOfBirthDay], [DateOfBirthYear], [CreditProfile], [MilitaryServiceYesNo], [CurrentLoanVAYesNo], [ForeclosureHistory], [BankruptcyYesNo], [BankruptcyHistory], [CreditCardDebtAmount], [RealtorConsultYesNo], [DebtConsultYesNo], [MortgageInsuranceYesNo], [EmailOptInYesNo], [HomeServicesOptInYesNo], [CurrentREAgentYesNo], [CreditScoreProductYesNo], [EduOptInYesNo], [CcMessageToBorrower], [SpouseDateOfBirthMonth], [SpouseDateOfBirthDay], [SpouseDateOfBirthYear]) 
VALUES (N'Prod_MortTree_Purchase', N'PROD', N'IE', N'mort-tree', N'2-0-0-0-0-0-1-0-0-3-2-0-1-0-1-0-0-1-0', N'&mpid=8550&devicemonitor=selenium', 
N'PURCHASE', N'Mobile/Manufactured home', N'Investment property', N'Montana', N'Helena', N'', N'59602', N'Y', N'', N'$950,001 - $1,000,000', N'0-5%', N'', N'', 
N'', N'', N'', N'', N'', N'', N'', N'default', N'default', N'', N'Otto', N'', N'Tester', N'', N'11115 Rushmore Dr', N'28277', 
N'704', N'541', N'5351', N'407', N'939', N'3463', N'', N'N', N'default', N'default', N'default', N'05', N'05', N'1955', N'Good', N'N', N'', N'Currently in foreclosure', 
N'Y', N'1-12 months ago', N'$7500 - $9,999', N'N', N'N', N'N', N'N', N'N', N'Y', N'N', N'N', N'', N'', N'', N'')
GO

INSERT [dbo].[tTestData_Mortgage] ([TestCaseName], [TestEnvironment], [BrowserType], [Template], [Variation], [QueryString], [LoanType], [HomeDescription], [PropertyUseType], [PropertyState], [PropertyCity], [PropertyStreet], [PropertyZipCode], [FoundNewHomeYesNo], [FirstTimeBuyerYesNo], [PurchasePrice], [PurchaseDownPayment], [RefiPropertyValue], [FirstMortgageBalance], [FirstMortgagePayment], [FirstMortgageRate], [SecondMortgageYesNo], [SecondMortgageBalance], [SecondMortgagePayment], [SecondMortgageRate], [RefiCashoutAmount], [EmailAddress], [Password], [ConfirmPassword], [BorrowerFirstName], [BorrowerMiddleName], [BorrowerLastName], [BorrowerSuffix], [BorrowerStreetAddress], [BorrowerZipCode], [BorrowerHomePhone1], [BorrowerHomePhone2], [BorrowerHomePhone3], [BorrowerWorkPhone1], [BorrowerWorkPhone2], [BorrowerWorkPhone3], [BorrowerWorkPhoneExt], [WorkPhoneSameAsHomeYesNo], [BorrowerSsn1], [BorrowerSsn2], [BorrowerSsn3], [DateOfBirthMonth], [DateOfBirthDay], [DateOfBirthYear], [CreditProfile], [MilitaryServiceYesNo], [CurrentLoanVAYesNo], [ForeclosureHistory], [BankruptcyYesNo], [BankruptcyHistory], [CreditCardDebtAmount], [RealtorConsultYesNo], [DebtConsultYesNo], [MortgageInsuranceYesNo], [EmailOptInYesNo], [HomeServicesOptInYesNo], [CurrentREAgentYesNo], [CreditScoreProductYesNo], [EduOptInYesNo], [CcMessageToBorrower], [SpouseDateOfBirthMonth], [SpouseDateOfBirthDay], [SpouseDateOfBirthYear]) 
VALUES (N'Prod_MortTree_Refinance_Hybrid', N'PROD', N'IE', N'mort-tree', N'2-0-1-0-0-5', N'&mpid=8550&devicemonitor=selenium', 
N'REFINANCE', N'Mobile/Manufactured home', N'Investment property', N'Montana', N'Helena', N'', N'59602', N'', N'', N'', N'', N'Over $2,000,000', N'$900,001 - $950,000', 
N'Over $7,501', N'7.25%', N'N', N'', N'', N'', N'$0 No Cash', N'qa+random', N'default', N'', N'Otto', N'', N'Tester', N'', N'11115 Rushmore Dr', N'28277', 
N'704', N'541', N'5351', N'407', N'939', N'3463', N'', N'N', N'default', N'default', N'default', N'01', N'02', N'1973', N'Good', N'Y', N'N', N'Currently in foreclosure', 
N'Y', N'1-12 months ago', N'$7500 - $9,999', N'N', N'N', N'N', N'N', N'N', N'N', N'N', N'N', N'', N'', N'', N'')
GO

INSERT [dbo].[tTestData_Mortgage] ([TestCaseName], [TestEnvironment], [BrowserType], [Template], [Variation], [QueryString], [LoanType], [HomeDescription], [PropertyUseType], [PropertyState], [PropertyCity], [PropertyStreet], [PropertyZipCode], [FoundNewHomeYesNo], [FirstTimeBuyerYesNo], [PurchasePrice], [PurchaseDownPayment], [RefiPropertyValue], [FirstMortgageBalance], [FirstMortgagePayment], [FirstMortgageRate], [SecondMortgageYesNo], [SecondMortgageBalance], [SecondMortgagePayment], [SecondMortgageRate], [RefiCashoutAmount], [EmailAddress], [Password], [ConfirmPassword], [BorrowerFirstName], [BorrowerMiddleName], [BorrowerLastName], [BorrowerSuffix], [BorrowerStreetAddress], [BorrowerZipCode], [BorrowerHomePhone1], [BorrowerHomePhone2], [BorrowerHomePhone3], [BorrowerWorkPhone1], [BorrowerWorkPhone2], [BorrowerWorkPhone3], [BorrowerWorkPhoneExt], [WorkPhoneSameAsHomeYesNo], [BorrowerSsn1], [BorrowerSsn2], [BorrowerSsn3], [DateOfBirthMonth], [DateOfBirthDay], [DateOfBirthYear], [CreditProfile], [MilitaryServiceYesNo], [CurrentLoanVAYesNo], [ForeclosureHistory], [BankruptcyYesNo], [BankruptcyHistory], [CreditCardDebtAmount], [RealtorConsultYesNo], [DebtConsultYesNo], [MortgageInsuranceYesNo], [EmailOptInYesNo], [HomeServicesOptInYesNo], [CurrentREAgentYesNo], [CreditScoreProductYesNo], [EduOptInYesNo], [CcMessageToBorrower], [SpouseDateOfBirthMonth], [SpouseDateOfBirthDay], [SpouseDateOfBirthYear]) 
VALUES (N'Prod_MortTree_Purchase_Hybrid', N'PROD', N'firefox', N'mort-tree', N'2-0-0-0-0-5-1-0-0-3-2-2-1-0-2-0-0-1-0-1-1-0-1-1', N'&mpid=8550&devicemonitor=selenium', 
N'PURCHASE', N'Mobile/Manufactured home', N'Secondary home', N'Montana', N'Helena', N'', N'59602', N'Y', N'', N'$950,001 - $1,000,000', N'0-5%', N'', N'', 
N'', N'', N'', N'', N'', N'', N'', N'default', N'default', N'', N'Otto', N'', N'Tester', N'', N'11115 Rushmore Dr', N'28277', 
N'704', N'541', N'5351', N'407', N'939', N'3463', N'', N'N', N'default', N'default', N'default', N'05', N'05', N'1955', N'Good', N'N', N'', N'Currently in foreclosure', 
N'Y', N'1-12 months ago', N'$7500 - $9,999', N'N', N'N', N'N', N'N', N'N', N'Y', N'N', N'N', N'', N'', N'', N'')
GO

INSERT [dbo].[tTestData_Mortgage] ([TestCaseName], [TestEnvironment], [BrowserType], [Template], [Variation], [QueryString], [LoanType], [HomeDescription], [PropertyUseType], [PropertyState], [PropertyCity], [PropertyStreet], [PropertyZipCode], [FoundNewHomeYesNo], [FirstTimeBuyerYesNo], [PurchasePrice], [PurchaseDownPayment], [RefiPropertyValue], [FirstMortgageBalance], [FirstMortgagePayment], [FirstMortgageRate], [SecondMortgageYesNo], [SecondMortgageBalance], [SecondMortgagePayment], [SecondMortgageRate], [RefiCashoutAmount], [EmailAddress], [Password], [ConfirmPassword], [BorrowerFirstName], [BorrowerMiddleName], [BorrowerLastName], [BorrowerSuffix], [BorrowerStreetAddress], [BorrowerZipCode], [BorrowerHomePhone1], [BorrowerHomePhone2], [BorrowerHomePhone3], [BorrowerWorkPhone1], [BorrowerWorkPhone2], [BorrowerWorkPhone3], [BorrowerWorkPhoneExt], [WorkPhoneSameAsHomeYesNo], [BorrowerSsn1], [BorrowerSsn2], [BorrowerSsn3], [DateOfBirthMonth], [DateOfBirthDay], [DateOfBirthYear], [CreditProfile], [MilitaryServiceYesNo], [CurrentLoanVAYesNo], [ForeclosureHistory], [BankruptcyYesNo], [BankruptcyHistory], [CreditCardDebtAmount], [RealtorConsultYesNo], [DebtConsultYesNo], [MortgageInsuranceYesNo], [EmailOptInYesNo], [HomeServicesOptInYesNo], [CurrentREAgentYesNo], [CreditScoreProductYesNo], [EduOptInYesNo], [CcMessageToBorrower], [SpouseDateOfBirthMonth], [SpouseDateOfBirthDay], [SpouseDateOfBirthYear]) 
VALUES (N'Prod_Mortgage_Refinance', N'PROD', N'firefox', N'mortgage', N'2-1-1-1-0-1-0-0-0-0-2-1-0-0-1-0-0-1-0-1-3-1-0-0-0-0-0', N'&mpid=8550&devicemonitor=selenium', 
N'REFINANCE', N'Mobile/Manufactured home', N'Secondary home', N'Montana', N'Helena', N'', N'59602', N'', N'', N'', N'', N'Over $2,000,000', N'$900,001 - $950,000', 
N'Over $7,501', N'7.25%', N'N', N'', N'', N'', N'$0 No Cash', N'qa+random', N'default', N'', N'Otto', N'', N'Tester', N'', N'11115 Rushmore Dr', N'28277', 
N'704', N'541', N'5351', N'407', N'939', N'3463', N'', N'N', N'default', N'default', N'default', N'05', N'05', N'1955', N'Good', N'N', N'', N'Currently in foreclosure', 
N'Y', N'1-12 months ago', N'$7500 - $9,999', N'N', N'N', N'N', N'N', N'N', N'N', N'N', N'N', N'', N'', N'', N'')
GO

INSERT [dbo].[tTestData_Mortgage] ([TestCaseName], [TestEnvironment], [BrowserType], [Template], [Variation], [QueryString], [LoanType], [HomeDescription], [PropertyUseType], [PropertyState], [PropertyCity], [PropertyStreet], [PropertyZipCode], [FoundNewHomeYesNo], [FirstTimeBuyerYesNo], [PurchasePrice], [PurchaseDownPayment], [RefiPropertyValue], [FirstMortgageBalance], [FirstMortgagePayment], [FirstMortgageRate], [SecondMortgageYesNo], [SecondMortgageBalance], [SecondMortgagePayment], [SecondMortgageRate], [RefiCashoutAmount], [EmailAddress], [Password], [ConfirmPassword], [BorrowerFirstName], [BorrowerMiddleName], [BorrowerLastName], [BorrowerSuffix], [BorrowerStreetAddress], [BorrowerZipCode], [BorrowerHomePhone1], [BorrowerHomePhone2], [BorrowerHomePhone3], [BorrowerWorkPhone1], [BorrowerWorkPhone2], [BorrowerWorkPhone3], [BorrowerWorkPhoneExt], [WorkPhoneSameAsHomeYesNo], [BorrowerSsn1], [BorrowerSsn2], [BorrowerSsn3], [DateOfBirthMonth], [DateOfBirthDay], [DateOfBirthYear], [CreditProfile], [MilitaryServiceYesNo], [CurrentLoanVAYesNo], [ForeclosureHistory], [BankruptcyYesNo], [BankruptcyHistory], [CreditCardDebtAmount], [RealtorConsultYesNo], [DebtConsultYesNo], [MortgageInsuranceYesNo], [EmailOptInYesNo], [HomeServicesOptInYesNo], [CurrentREAgentYesNo], [CreditScoreProductYesNo], [EduOptInYesNo], [CcMessageToBorrower], [SpouseDateOfBirthMonth], [SpouseDateOfBirthDay], [SpouseDateOfBirthYear]) 
VALUES (N'Prod_Mortgage_Purchase', N'PROD', N'IE', N'mortgage', N'2-1-1-1-0-0-0-0-0-0-2-1-0-0-1-0-0-1-0-1-3-1-0-0-1-0-0', N'&mpid=8550&devicemonitor=selenium', 
N'PURCHASE', N'Mobile/Manufactured home', N'Investment property', N'Montana', N'Helena', N'', N'59602', N'Y', N'', N'$950,001 - $1,000,000', N'0-5%', N'', N'', 
N'', N'', N'', N'', N'', N'', N'', N'default', N'default', N'', N'Otto', N'', N'Tester', N'', N'11115 Rushmore Dr', N'28277', 
N'704', N'541', N'5351', N'407', N'939', N'3463', N'', N'N', N'default', N'default', N'default', N'01', N'02', N'1983', N'Good', N'Y', N'N', N'Currently in foreclosure', 
N'Y', N'1-12 months ago', N'$7500 - $9,999', N'N', N'N', N'N', N'N', N'N', N'Y', N'N', N'N', N'', N'', N'', N'')
GO

INSERT [dbo].[tTestData_Mortgage] ([TestCaseName], [TestEnvironment], [BrowserType], [Template], [Variation], [QueryString], [LoanType], [HomeDescription], [PropertyUseType], [PropertyState], [PropertyCity], [PropertyStreet], [PropertyZipCode], [FoundNewHomeYesNo], [FirstTimeBuyerYesNo], [PurchasePrice], [PurchaseDownPayment], [RefiPropertyValue], [FirstMortgageBalance], [FirstMortgagePayment], [FirstMortgageRate], [SecondMortgageYesNo], [SecondMortgageBalance], [SecondMortgagePayment],[SecondMortgageRate], [RefiCashoutAmount], [EmailAddress], [Password], [ConfirmPassword], [BorrowerFirstName], [BorrowerMiddleName], [BorrowerLastName], [BorrowerSuffix], [BorrowerStreetAddress], [BorrowerZipCode], [BorrowerHomePhone1], [BorrowerHomePhone2], [BorrowerHomePhone3], [BorrowerWorkPhone1], [BorrowerWorkPhone2], [BorrowerWorkPhone3], [BorrowerWorkPhoneExt], [WorkPhoneSameAsHomeYesNo], [BorrowerSsn1], [BorrowerSsn2], [BorrowerSsn3], [DateOfBirthMonth], [DateOfBirthDay], [DateOfBirthYear], [CreditProfile], [MilitaryServiceYesNo], [CurrentLoanVAYesNo], [ForeclosureHistory], [BankruptcyYesNo], [BankruptcyHistory], [CreditCardDebtAmount], [RealtorConsultYesNo], [DebtConsultYesNo], [MortgageInsuranceYesNo], [EmailOptInYesNo], [HomeServicesOptInYesNo], [CurrentREAgentYesNo], [CreditScoreProductYesNo], [EduOptInYesNo], [CcMessageToBorrower], [SpouseDateOfBirthMonth], [SpouseDateOfBirthDay], [SpouseDateOfBirthYear]) 
VALUES (N'Prod_ReverseMortgage_Fieldset0', N'PROD', N'firefox', N'reverse-mortgage', N'0-0-0-0-1-0-0-0', N'&mpid=8550&devicemonitor=selenium', 
N'REFINANCE', N'Single family home', N'Primary residence', N'Montana', N'Helena', N'', N'59602', N'', N'', N'', N'', N'$190,001 - $200,000', N'$10,001 - $20,000', 
N'', N'', N'', N'', N'', N'', N'', N'default', N'default', N'', N'Otto', N'', N'Tester', N'', N'131 Test St', N'59602', 
N'407', N'939', N'3463', N'', N'', N'', N'', N'N', N'default', N'default', N'default', N'01', N'01', N'1950', N'', N'', N'', N'', 
N'', N'', N'', N'N', N'N', N'N', N'N', N'N', N'N', N'N', N'N', N'', N'12', N'31', N'1945')
GO

INSERT [dbo].[tTestData_Mortgage] ([TestCaseName], [TestEnvironment], [BrowserType], [Template], [Variation], [QueryString], [LoanType], [HomeDescription], [PropertyUseType], [PropertyState], [PropertyCity], [PropertyStreet], [PropertyZipCode], [FoundNewHomeYesNo], [FirstTimeBuyerYesNo], [PurchasePrice], [PurchaseDownPayment], [RefiPropertyValue], [FirstMortgageBalance], [FirstMortgagePayment], [FirstMortgageRate], [SecondMortgageYesNo], [SecondMortgageBalance], [SecondMortgagePayment],[SecondMortgageRate], [RefiCashoutAmount], [EmailAddress], [Password], [ConfirmPassword], [BorrowerFirstName], [BorrowerMiddleName], [BorrowerLastName], [BorrowerSuffix], [BorrowerStreetAddress], [BorrowerZipCode], [BorrowerHomePhone1], [BorrowerHomePhone2], [BorrowerHomePhone3], [BorrowerWorkPhone1], [BorrowerWorkPhone2], [BorrowerWorkPhone3], [BorrowerWorkPhoneExt], [WorkPhoneSameAsHomeYesNo], [BorrowerSsn1], [BorrowerSsn2], [BorrowerSsn3], [DateOfBirthMonth], [DateOfBirthDay], [DateOfBirthYear], [CreditProfile], [MilitaryServiceYesNo], [CurrentLoanVAYesNo], [ForeclosureHistory], [BankruptcyYesNo], [BankruptcyHistory], [CreditCardDebtAmount], [RealtorConsultYesNo], [DebtConsultYesNo], [MortgageInsuranceYesNo], [EmailOptInYesNo], [HomeServicesOptInYesNo], [CurrentREAgentYesNo], [CreditScoreProductYesNo], [EduOptInYesNo], [CcMessageToBorrower], [SpouseDateOfBirthMonth], [SpouseDateOfBirthDay], [SpouseDateOfBirthYear]) 
VALUES (N'Prod_ReverseMortgage_Fieldset1', N'PROD', N'IE', N'reverse-mortgage', N'0-0-0-1-1-0-0-0', N'&mpid=8550&devicemonitor=selenium', 
N'REFINANCE', N'Townhome', N'Primary residence', N'Montana', N'Helena', N'', N'59602', N'', N'', N'', N'', N'$600,001 - $650,000', N'$100,001 - $105,000', 
N'', N'', N'', N'', N'', N'', N'', N'default', N'default', N'', N'Otto', N'', N'Tester', N'', N'131 Test St', N'59602', 
N'407', N'939', N'3463', N'', N'', N'', N'', N'N', N'default', N'default', N'default', N'01', N'01', N'1950', N'', N'', N'', N'', 
N'', N'', N'', N'N', N'N', N'N', N'N', N'N', N'N', N'N', N'N', N'', N'12', N'31', N'1945')
GO


